### ISSUE TITLE
MSW (Mock Service Worker) 도입

### ISSUE THREAD

**Issue by davidktlee** [Kernel360/f1-Yigil#130]
### 📝Description
- 서비스 워커를 이용해 네트워크 요청을 가로채는 API 모킹 라이브러리를 도입합니다.
- 백엔드 API 개발과 프론트엔드 개발이 동시에 이루어지기 때문에, Mock 데이터를 사용하기 위해 도입합니다.

### ✅Task
- [x] MSW 환경설정
- [x] MSW Mock 데이터 테스트

### ✍️Additional
- API 요청과 응답이 이루어지기 때문에 초반에 논의하였던 [`Zod`](https://zod.dev/) validation 라이브러리 사용에 대해 논의 할 필요가 있음.
  - 장점으로는 런타임 중 타입을 엄격히 검사해 프론트와 백엔드의 합의되지 않은 데이터의 정확한 유효성 검사가 가능함. 
    (타입스크립트는 컴파일 과정에서만 에러 발생)
  - 단점으로는 유연성이 필요한 경우 제한적일 수 있으며 처음 사용하는 경우 학습하는데 시간을 투자해야 함.

**Comment by hatchling13** [comment]
`Zod` 가 해결하는 문제는 어디까지나 '런타임 `데이터 유효성` 검증'이고, 이를 TypeScript로 지원하는 접근 방식을 취하고 있기 때문에 타입 검사와는 사실 큰 관련이 없다고 볼 수 있습니다(때문에 TS 환경이 아니어도 사용할 수 있습니다).

`Zod`는 JS의 [`원시 타입`](https://zod.dev/?id=primitives)을 조합하는 방식으로 스키마를 만드는 방식이기 때문에, 유연성의 경우 크게 문제가 없을 것으로 생각합니다(`any` 타입도 받을 수 있습니다).

**Comment by davidktlee** [comment]
## 건의 사항
`Jest` 테스트 라이브러리를 `Vitest` 테스트 라이브러리로의 마이그레이션을 건의 드리려 합니다.

## 건의 이유
MSW 환경 설정 후 테스트 코드 작성 시에 `Jest` 테스팅 라이브러리와 많은 에러가 발생.
[`홈페이지`](https://mswjs.io/docs/faq#requestresponsetextencoder-is-not-defined-jest)에도 문제점이 명시되어 있고 해결 방법도 있지만, 문제를 해결하기 위해 `polyfill` 파일 작성 및 코드가 `Vitest` 를 사용했을 때 보다 상대적으로 많이 늘어난다고 판단해 건의하게 됨.
## 문제점 
1. `ReferenceError: TextEncoder is not defined`
`jest`에서 msw 모킹 함수를 호출하려고 하면 위와 같은 에러가 뜹니다.
=> 해결 방법으로 `jest.polyfills.js` 생성, 코드 작성 `jest.config.js` 파일에 코드 작성이 필요합니다.
또 이 파일을 적용시키려면 `undici` 라는 라이브러리도 설치해야 합니다.
```
// jest.polyfills.js
const { TextDecoder, TextEncoder } = require('node:util')
Object.defineProperties(globalThis, {
  TextDecoder: { value: TextDecoder },
  TextEncoder: { value: TextEncoder },
})
const { Blob, File } = require('node:buffer')
const { fetch, Headers, FormData, Request, Response } = require('undici')
Object.defineProperties(globalThis, {
  fetch: { value: fetch, writable: true },
  Blob: { value: Blob },
  File: { value: File },
  Headers: { value: Headers },
  FormData: { value: FormData },
  Request: { value: Request },
  Response: { value: Response },
})
// jest.config.js
setupFiles: ['./jest.polyfills.js'],
  testEnvironmentOptions: {
    customExportConditions: [''],
  },
```
2. `ReferenceError: ReadableStream is not defined`
1번의 해결 방법으로 1번의 에러를 해결했을 때, 2번 에러가 납니다.
2번의 에러는 `undici` 라이브러리를 5버전으로 다운 그레이드하고 `jest.polyfill.js` 파일에 설정을 추가하면 되는데 또 새로운 에러가 납니다.
```
const { TextDecoder, TextEncoder, ReadableStream } = require('node:util') // ReadableStream 추가
```
3. `ReferenceError: clearImmediate is not defined`
3번 에러가 난 후에 이렇게 연쇄적으로 에러가 나고 버전을 다운그레이드 하면서 개발을 하다보면 나중에 관련된 라이브러리의 버전이 변경되었을 때 디버깅 하기 너무 힘들 것 같다는 생각이 들었습니다.

## 해결 방법
대체 방안인 `Vitest`로 MSW를 이용한 테스트를 해보니 잘 동작해서 `Vitest` 테스트 라이브러리로 변경해 진행하면 좋을 것 같습니다.

**Comment by hatchling13** [comment]
https://vitest.dev/guide/migration.html#migrating-from-jest

공식 문서의 해당 부분에 Jest에서 Vitest로 마이그레이션 시 신경써야할 부분을 짚어주고 있습니다.

https://nextjs.org/docs/app/building-your-application/testing/vitest

이러한 부분을 신경써서 마이그레이션을 진행하면 되겠습니다.

**Comment by hatchling13** [comment]
작업은 경택님께서 진행하실 예정인가용?

**Comment by davidktlee** [comment]
테스트 코드의 변경은 없을 것 같아서 `Vitest` 환경설정까지 제가 해서 push 하도록 하겠습니다!
