### ISSUE TITLE
어드민 서비스를 위한, 어드민 모듈 추가

### ISSUE THREAD

**Issue by stoneHee99** [Kernel360/f1-Yigil#170]
### 📝Description
어드민 관련 서비스를 추가하기 위해, admin-api 모듈을 생성합니다.

### ✅Task
- [x] 어드민 API 모듈 생성
- [x] 어드민 frontend 프로젝트 생성 (Next.js)  

### ✍️Additional
- 어드민 프론트엔드의 경우 백엔드 개발자 분들이 작업하느라 미숙해서 테스트 작업을 러닝커브를 끌어올린 이후로 미루고자 합니다.
- 또한 어드민 사이트 작업 자체는 프론트까지 백엔드 분들이 작업하되, 리뷰 정도를 요청드려도 될지 문의드립니다! 
@hatchling13  @davidktlee

**Comment by davidktlee** [comment]
언제든 좋습니다~

**Comment by hatchling13** [comment]
언제든 요청주세요~
