### ISSUE TITLE
일정 추가하기 기능 구현

### ISSUE THREAD

**Issue by davidktlee** [Kernel360/f1-Yigil#200]
### 📝Description
현재 디자인에서 장소만 추가할 수 있는 기능과 장소와 일정을 같이 추가할 수 있는 기능이 나와있는데 장소와 일정을 같이 추가하는 기능을 구현할 예정입니다.
일정 추가의 흐름을 정리하면 
1. 장소 검색
2. 장소 선택 
  2-1. 장소 선택 완료 시 지도 내의 순서도에 순차대로 자동 입력
3. 각 장소의 이름과 주소 확인 
4. 사진 업로드 (디자인 상 현재 최대 5장)
5. 각 장소에 대한 별점 등록
6. 각 장소에 대한 리뷰 등록
7. 일정 제목 작성 및 일정에 대한 리뷰 작성
  7-1. 작성 시 지도에 마커로 순서 표시

이런 흐름이 될 것 같습니다.
### ✅Task
- [ ] 지도 컴포넌트 
  - [ ] 인포 윈도우 추가 및 마커 표시
  - [ ] 순서도 표시
- [ ] 사진 업로드
- [ ] 별점 및 리뷰
- [ ] 일정 확인 및 마커 포함한 지도 표시

### ✍️Additional
정욱님이 만들고 계신 검색 컴포넌트가 완성되면 검색 컴포넌트와 연동해 지도 검색이 가능하도록 만들어야 합니다.
네이버 지도 라이브러리인 [`react-naver-maps`](https://zeakd.github.io/react-naver-maps/) 의 사용 여부를 결정해야 합니다.
[`static maps`](https://api.ncloud-docs.com/docs/ai-naver-mapsstaticmap-raster)를 이용해 아래 디자인을 구현 후 백엔드에 네이버에서 받아온 이미지를 보내서 상세 페이지에서도 네이버 지도를 호출하지 않고 백엔드에서 이미지 데이터를 받아와서 사용하면 좋을 것 같은데 @hatchling13 님과 백엔드분들과 상의가 필요한 부분입니다.
<img width="213" alt="스크린샷 2024-01-30 오후 12 33 25" src="https://github.com/Kernel360/f1-Yigil/assets/97086762/e441a353-cf02-4c18-820d-37167aee5491">
<img width="281" alt="스크린샷 2024-01-30 오후 12 37 06" src="https://github.com/Kernel360/f1-Yigil/assets/97086762/d080bd13-a68d-4970-af78-74b08fc6c700">

**Comment by davidktlee** [comment]
기능 구현의 우선 순위에서 밀렸기 때문에 일단은 장소 추가에서 각각의 기능으로 세분화 한 후에 그 기능을 먼저 작업 후 작업 예정입니다.

**Comment by hatchling13** [comment]
#589, #595 에서 작업이 완료되었으므로 닫음 처리합니다.
