### ISSUE TITLE
fetch 함수 재사용에 따른 문제점 해결책 고민하기

### ISSUE THREAD

**Issue by hatchling13** [Kernel360/f1-Yigil#333]
### 📝Description
#235 에서 시작되고 #237 에서 작업된 `httpRequest` 내 fetch 함수 재사용 현황을 재고해볼 필요가 있습니다.
현재 구현 상태에 대하여 고려해볼 점이 크게 두 가지가 있습니다.
#### 1. `Next.js` 프레임워크 구현 상세에 따른 문제
`Next.js` App Router는 표준 fetch API를 확장하여, 자체적인 캐싱 시스템을 구축해놓은 상태입니다. 표준 `fetch`의 두 번째 파라미터 [`option: RequestInit`](https://developer.mozilla.org/en-US/docs/Web/API/fetch#options)의 `cache` 프로퍼티가 수정되었으며, `revalidate`/`tag` 프로퍼티가 있는 `next` 프로퍼티가 추가되어있습니다. 하나의 `fetch`를 최대한 재사용하기 위해 구현된 현재 상태로는 `Next.js`의 자체 캐시를 관리할 수 없습니다. 해당 속성을 위한 커링을 별도로 더 할 수도 있겠지만, 해당 추상화로 인해 원하는 동작이 나오지 않는 이유를 탐색하기 힘들었다는 소감을 말씀드리고 싶습니다.
#### 2. `Next.js` 14.1 버전에서의 빌드 실패
`Next.js` 버전을 올리니 코드가 같은데도 프로젝트 빌드가 계속 실패합니다. 대부분의 오류가 `A "use server" file can only export async functions, found object.`이라는 문구와 함께 발생했는데요. 빌드할 때마다 맨 마지막에 뜨는 문구 `Failed to collect page data for ${page}`의 `${page}` 부분에 들어가는 URL 내용에 `/mypage/*` 라는 값이 많이 보이긴 합니다. 정확히 어떤 문제 때문인지 확답을 내기는 힘들지만, 빌드가 안되는 거면 저희가 코드를 잘못 쓰고 있는 부분이 있는거겠죠... `"use server"` 언급이 나오니까 서버 액션 관련 내용이겠거니 짐작은 하고 있는데, 윗 문단의 마지막 줄에서도 말씀드렸다시피 어떤 부분에 문제가 있는지 추적하기가 어렵습니다.

이상의 내용에 따라, 현재 구조에 대해 다시 생각해봐야 할 것 같습니다. 

### ✅Task
- 이 이슈는 의견 교환을 위한 것으로, 별도의 작업을 명시하지 않습니다.

### ✍️Additional
의견 교환을 위해 @davidktlee 님을 태그합니다.

**Comment by davidktlee** [comment]
### 1. Next.js 프레임워크 구현 상세에 따른 문제
1번 문제는 커링 함수의 다양성과 확장성을 고려하지 못하고 작성을 한 것 같네요.
`next`에서 사용할 수 있는 `fetch` 함수의 다양한 기능과 옵션을 사용하도록 고려해 작성 하지 못했고 다양한 방법으로 사용을 할 때마다 커링 함수가 다른 방법으로 재작성 된다면 재사용하려고 작성해 둔 커링 `fetch` 함수의 의미는 퇴색되는 것 같아 기본 `fetch` 함수를 사용하되, 관심사에 따라 분리하는 방법을 사용하는 쪽으로 변경을 하도록 생각해야 할 것 같습니다.
추상화로 디버깅하기 어려웠다는 말씀은 쿠키나 여러 파라미터를 사용했을 때 함수가 원하는 대로 동작하지 않았을 경우 디버깅하는데 어려움을 겪었다는 말씀으로 이해해도 될까요?

### 2. Next.js 14.1 버전에서의 빌드 실패
2번 문제는 커링 함수와는 관련이 없는 것 같고 서버 액션을 작성하는 `app/_components/mypage/hooks/myPageActions.ts` 파일에서 객체를  `export` 하고 있어서 나는 문제로 보입니다.

**Comment by hatchling13** [comment]
1. 함수가 실행되는 단계를 따라가보며 실제로 어디에 문제가 있는지를 탐색해야 하는데, 잘 동작한다고 생각했던 부분에 근본적으로 문제가 있어버리니 생각의 전환이 되지 않았습니다. `requestWithCookie`나 requestWithoutCookie` 같은 부분은 당연히 되어야한다는 어떤 고정관념이 잡혀버리니, 그 하위에 있던 fetch 자체를 건드리게 될줄은 몰랐거든요...

2. 버전을 올린 후, 빌드가 깨져서 해당 부분만 고치면 되나 싶어서 고쳐봤는데 에러가 꼬리에 꼬리를 물고 일어나서 도중에 도망쳤거든요 ㅋㅋ... 그래서 뭔가 처음부터 잘못된 길을 갔나 싶어서 푸념 비스무리하게 해봤습니다. 시간이 좀 남으신다면 현재 구조에서 버전만 올리신 다음에 고쳐보시겠어요? 저는 못 잡았지만 경택님은 잡으실 수도 있으니까요!
